version: '3.9'

services:
  frontend:
    build: frontend/
    ports:
      - "5173:5173"
    networks:
      - "mtrack-network"
  backend:
    build: backend/
    ports:
      - "4000:4000"
    networks:
      - "mtrack-network"
    depends_on:
      - frontend
    env_file:
      - ./backend/.env

networks:
  mtrack-network:
    driver: bridge